/// The model/geometry/edit types DESCENDED to @tf-hwp/editor-core (issue 026) — they are DOM-free shapes,
/// so they live in the headless core and @tf-hwp/react RE-EXPORTS them here verbatim. Existing hosts keep
/// `import type { Anchor, Intent, ... } from "@tf-hwp/react"` working unchanged (backward compatible).
///
/// The selection VIEW types the components draw (Mark/Marquee/Sel) map 1:1 onto the core's
/// SelMark/SelMarquee/Selection — aliased below so component code reads naturally.
export type {
  Anchor,
  BlockHit,
  TableBox,
  TableGrid,
  GridCell,
  CellHit,
  ImageBox,
  Intent,
  Outcome,
  OpenResult,
  OutlineItem,
  DocContext,
  OnAiRequest,
  IntentCard,
  Box,
  Selection,
  SelMark,
  SelMarquee,
  PointerInput,
  PageGeom,
  RunSpec,
  CellRange,
  CellFmt,
  PageMarginsMm,
  HitResult,
  CaretRect,
  CellCaretRect,
  CellTextHit,
  TextAnchor,
  FindMatch,
  FindOptions,
  FindReplaceOptions,
  ReplaceResult,
  MatchBox,
} from "@tf-hwp/editor-core";
