import { useEffect, useRef } from "react";
import { useWorkspaceMessages } from "../i18n";

export interface PdfPreviewDialogProps {
  /** Blob URL of the GENERATED PDF bytes (the host owns creation + revocation). */
  url: string;
  /** Suggested filename shown in the header and used by 다운로드. */
  filename: string;
  /** Page count reported by the engine, when known — shown next to the filename (정직한 표시). */
  pages?: number;
  /** Save the previewed bytes to disk (the host runs its usual download/onExport lane). */
  onDownload: () => void;
  /** Close the preview (Esc · 닫기 · backdrop click). The host revokes the blob URL here. */
  onClose: () => void;
}

/// PdfPreviewDialog (이슈 6) — the PDF button no longer dumps a file into the download folder and hopes
/// it looks right: it opens THIS modal with the freshly generated bytes in an `<iframe>` (the browser's
/// own PDF viewer), so a user can compare it against the on-screen document BEFORE saving. 다운로드 saves
/// the SAME bytes that are being previewed (no second export — no chance of a different render).
///
/// Deliberately dumb: it owns no export logic, no blob lifetime (the host creates + revokes the URL), and
/// no engine access. Esc / backdrop / 닫기 all route to `onClose`. Individually importable so a host can
/// reuse the preview surface over its own export lane.
export function PdfPreviewDialog({ url, filename, pages, onDownload, onClose }: PdfPreviewDialogProps) {
  const msg = useWorkspaceMessages();
  const closeRef = useRef<HTMLButtonElement>(null);

  // Esc closes. Bound on the window (capture) so it works regardless of focus — including while focus is
  // inside the PDF `<iframe>`'s own document, where our React handlers never see the key.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.stopPropagation();
        onClose();
      }
    };
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [onClose]);

  // Move focus into the dialog so Esc/Tab land here and a screen reader announces the preview.
  useEffect(() => {
    closeRef.current?.focus();
  }, []);

  return (
    <div
      className="hw-pdfpreview-backdrop"
      data-testid="pdf-preview"
      role="dialog"
      aria-modal="true"
      aria-label={msg.workspace.pdfPreviewTitle}
      onPointerDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="hw-pdfpreview">
        <div className="hw-pdfpreview-head">
          <span className="hw-pdfpreview-title">{msg.workspace.pdfPreviewTitle}</span>
          <span className="hw-pdfpreview-name" title={filename}>
            {filename}
            {typeof pages === "number" ? ` · ${msg.workspace.pdfPreviewPages(pages)}` : ""}
          </span>
          <span className="hw-spacer" />
          <button className="hw-pdfpreview-download" onClick={onDownload} data-testid="pdf-preview-download">
            {msg.workspace.pdfPreviewDownload}
          </button>
          <button ref={closeRef} className="hw-pdfpreview-close" onClick={onClose} data-testid="pdf-preview-close">
            {msg.workspace.pdfPreviewClose}
          </button>
        </div>
        {/* The browser's built-in PDF viewer renders the blob. `title` is the accessible name. */}
        <iframe className="hw-pdfpreview-frame" src={url} title={msg.workspace.pdfPreviewTitle} data-testid="pdf-preview-frame" />
      </div>
    </div>
  );
}
